version: "3"

services:
    web:
        restart: always
        build: ./web
        ports:
            - "8000:18080" # flask
        volumes:
            - ./web:/app
        env_file: 
          - .env
          - .env_secret
        command: ./bootup.sh


