version: "3"


volumes:
  redisdata:

services:
    web:
        restart: always
        build: ./web
        ports:
            - "8000:18080" # flask
        volumes:
            - ./web:/app
        env_file: 
            - .env
            - .env_secret
        environment:
            - FLASK_APP=run.py
            - PORT=18080 # flask
        command: gunicorn -c /app/gunicorn_conf.py run:app

    redis:
        restart: always
        image: redis:latest
        expose:
            - "6379"
        volumes:
            - redisdata:/data


