version: "3"

services:
    web:
        restart: always
        build: ./web
        ports:
            - "8000:18080" # flask
        volumes:
            - ./web:/app
        env_file: 
            - .env
            - .env_secret
        environment:
            - FLASK_APP=run.py
            - PORT=18080 # flask
        command: gunicorn -c /app/gunicorn_conf.py run:app


