FROM python:3.8

RUN pip install --upgrade pip
RUN pip install flask
RUN pip install flask-wtf
RUN pip install flask-sqlalchemy
RUN pip install flask-bcrypt
RUN pip install flask-login
RUN pip install email_validator
RUN pip install pytest

RUN mkdir -p /app

WORKDIR /app
